#!/usr/bin/env bash

set -euo pipefail

temp="$(mktemp)"

subsystems_file="netlink-bindings/subsystems"
lib_rs="netlink-bindings/src/lib.rs"
cargo_tomls=("netlink-bindings/Cargo.toml" "reverse-lookup/Cargo.toml")

marker_line="Generated by $(basename -- $0) script. Do not modify."

subsystems=()
for i in netlink-bindings/src/*/; do
  i="$(basename -- "$i")"
  case "$i" in
  builtin) continue ;;
  esac
  subsystems+=("$i")
done

echo_until_marker() {
  while read -r line; do
    printf "%s\n" "$line"
    if [ "$line" = "$2" ]; then
      return
    fi
  done <"$1"

  printf "Didn't found marker in \"%q\": %s\n" "$1" "$2" >&2
  exit 1
}

for i in "${subsystems[@]}"; do
  printf "%s\n" "$i"
done >"$temp"
mv -v -- "$temp" "$subsystems_file"

{
  echo_until_marker "$lib_rs" "// $marker_line"

  for i in "${subsystems[@]}"; do
    echo
    echo "#[cfg(feature = \"$i\")]"
    echo "#[cfg_attr(docsrs, doc(cfg(feature = \"$i\")))]"
    if [[ "$i" = *-* ]]; then
      echo "#[path = \"$i/mod.rs\"]"
    fi
    echo "pub mod ${i/-/_};"
  done

} >"$temp"
mv -v -- "$temp" "$lib_rs"

for cargo_toml in "${cargo_tomls[@]}"; do
  {
    echo_until_marker "$cargo_toml" "# $marker_line"

    for i in "${subsystems[@]}"; do
      features=
      if [[ "$cargo_toml" = "reverse-lookup"* ]]; then
        features=" \"netlink-bindings/$i\" "
      fi
      printf "%s = [%s]\n" "$i" "$features"
    done

    echo
    echo "all-subsystems = ["
    for i in "${subsystems[@]}"; do
      printf "  \"%s\",\n" "$i"
    done
    echo "]"
  } >"$temp"
  mv -v -- "$temp" "$cargo_toml"
done
